//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WLED.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WLED.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a light manually:.
        /// </summary>
        internal static string AddLight {
            get {
                return ResourceManager.GetString("AddLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something happened, and we couldn&apos;t process your picture. Please try again. If this happens again, get in touch..
        /// </summary>
        internal static string CameraExceptionDesc {
            get {
                return ResourceManager.GetString("CameraExceptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error..
        /// </summary>
        internal static string CameraExceptionTitle {
            get {
                return ResourceManager.GetString("CameraExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to light..
        /// </summary>
        internal static string CannotConnect {
            get {
                return ResourceManager.GetString("CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on devices to hide them!.
        /// </summary>
        internal static string ClickHint {
            get {
                return ResourceManager.GetString("ClickHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (New Light).
        /// </summary>
        internal static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Device.
        /// </summary>
        internal static string DeviceAddPageTitle {
            get {
                return ResourceManager.GetString("DeviceAddPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete or Hide Devices.
        /// </summary>
        internal static string DeviceModificationTitle {
            get {
                return ResourceManager.GetString("DeviceModificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover lights....
        /// </summary>
        internal static string DiscoverLights {
            get {
                return ResourceManager.GetString("DiscoverLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        internal static string Effects {
            get {
                return ResourceManager.GetString("Effects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not seem to have a camera, or the camera is not responding. If you think this is a mistake, get in touch..
        /// </summary>
        internal static string FeatureNotSupportedDesc {
            get {
                return ResourceManager.GetString("FeatureNotSupportedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use this feature..
        /// </summary>
        internal static string FeatureNotSupportedTitle {
            get {
                return ResourceManager.GetString("FeatureNotSupportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find lights in your network:.
        /// </summary>
        internal static string FindLights {
            get {
                return ResourceManager.GetString("FindLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check it is plugged in, and try again..
        /// </summary>
        internal static string InstructionLabel {
            get {
                return ResourceManager.GetString("InstructionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address or URL.
        /// </summary>
        internal static string IPLabel {
            get {
                return ResourceManager.GetString("IPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED Preferences.
        /// </summary>
        internal static string LEDPreferences {
            get {
                return ResourceManager.GetString("LEDPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (get from device).
        /// </summary>
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NightLight.
        /// </summary>
        internal static string NightLight {
            get {
                return ResourceManager.GetString("NightLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found no lights yet....
        /// </summary>
        internal static string NoLightsFound {
            get {
                return ResourceManager.GetString("NoLightsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other lights!.
        /// </summary>
        internal static string OtherLights {
            get {
                return ResourceManager.GetString("OtherLights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you have not granted the app the permission to use the camera. To use this feature, please go to your device&apos;s settings and allow WLED to use the camera. Your pictures will only be manipulated locally..
        /// </summary>
        internal static string PermissionNotGrantedDesc {
            get {
                return ResourceManager.GetString("PermissionNotGrantedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need your permission to use this feature..
        /// </summary>
        internal static string PermissionNotGrantedTitle {
            get {
                return ResourceManager.GetString("PermissionNotGrantedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to reach your light....
        /// </summary>
        internal static string ReachingLight {
            get {
                return ResourceManager.GetString("ReachingLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security &amp; Updates.
        /// </summary>
        internal static string SecurityUpdates {
            get {
                return ResourceManager.GetString("SecurityUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop discovery.
        /// </summary>
        internal static string StopDiscovery {
            get {
                return ResourceManager.GetString("StopDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Interfaces.
        /// </summary>
        internal static string SyncInterfaces {
            get {
                return ResourceManager.GetString("SyncInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time &amp; Macros.
        /// </summary>
        internal static string TimeMacros {
            get {
                return ResourceManager.GetString("TimeMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the + button to add your WLED lights!.
        /// </summary>
        internal static string WelcomeInstruction {
            get {
                return ResourceManager.GetString("WelcomeInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WiFi Setup.
        /// </summary>
        internal static string WiFiSetup {
            get {
                return ResourceManager.GetString("WiFiSetup", resourceCulture);
            }
        }
    }
}
